
name: Action Sample

on:
  push:

  workflow_dispatch:

jobs:
  exec-unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - uses: actions/checkout@v2
      - name: install modules
        run: |
          pip install pytest==6.2.5
          pip install Flask==1.0.2
          pip install python-dotenv==0.19.2
          pip install Jinja2==3.0.1
          pip install itsdangerous==2.0.1
          pip list
      - name: unit test
        run:
          pytest